### ISSUE TITLE
Rename this preset

### ISSUE THREAD

**Issue by jamesplease** [yoshuawuyts/babel-preset-es2020#1]
I think this package name is going to cause a lot of unintentional problems in 2 years.

As you may know, Babel's naming scheme uses this same format for their yearly releases of stage4 proposals. In ~1 year, Babel will make `babel-preset-es2019` (this will happen after `es2018` is released, and a proposal reaches stage 4).

In 2 years, they will want to use this package name. Since you've taken it for this project, a huge number of developers will accidentally install this package into their projects, rather than the preset they actually want, and probably get unexpected results. This could cause them to waste a lot of time debugging the problem.

I'm guessing that it's not your intention to waste developers' time in a few years. It seems like your main goal is to take a stance against all of the fancy new (and possibly unnecessary) features in ES. This is a cool stance to take, and I'm glad you're being vocal about it. I just think you can accomplish those goals without any collateral damage.

---

Just to throw some numbers out there:

[babel-preset-es2015](https://www.npmjs.com/package/babel-preset-es2015): ~4m downloads per month
[babel-preset-es2017](https://www.npmjs.com/package/babel-preset-es2017) - ~700k downloads per month
[babel-preset-es2020](https://www.npmjs.com/package/babel-preset-es2020) - 1k downloads per month

In just a few years, a million or more accidental downloads per month could be caused by this package's name.

**Comment by yoshuawuyts** [comment]
This is equal parts artistic expression as actual production code. Let's revisit this issue in 2 years time

**Comment by jamesplease** [comment]
That seems like a strange decision to me, but you're the boss.

**Comment by yoshuawuyts** [comment]
Can't argue with ✨ art ✨

**Comment by jamiebuilds** [comment]
Hey @yoshuawuyts!

The Babel team has to communicate with a lot of different people around the world, and the slightest bit of confusion can cause tons of work for them. It would be nice if we could resolve this name collision now rather than in 2 years when people start installing it by mistake.

Would you mind changing it? I know the people working on it now would really appreciate it.

**Comment by yoshuawuyts** [comment]
Heya @thejameskyle 👋 - You've been rather rude to me in the past and enjoy the privilege of being on my very short list of people I've had to block on Twitter. I don't particularly enjoy y'all creeping up on my project like this (or for that matter, [already starting to call me out in public](https://twitter.com/jmeaspls/status/841435621272956928)).

As stated before, this is not an issue right now, and frankly I don't wanna be dealing with this on a Monday evening at 1am. So let's revisit this in two years time or so when you actually have a use for this package, and enjoy some art in the meantime alright? Alright.

<img width="735" alt="screen shot 2017-03-14 at 00 59 07" src="https://cloud.githubusercontent.com/assets/2467194/23880053/7e02dc9c-0851-11e7-9b0e-e4dda7e42945.png">
